language: clojure
jdk: openjdk10
lein: 2.8.1
before_install:
  - rm "${JAVA_HOME}/lib/security/cacerts"
  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
  - lein doo phantom test once
  - lein cljsbuild once release
  - lein less once
deploy:
  provider: releases
  api_key:
    secure: ObliMV9vtePzP2csggfS2bpK8Q4k1FZpOJhJn0CGH23C5Y/BmmofMdRLzUGOHx8EHCSe5GBkkEnkVKYQ5LGHHe1EbAWLvF3wMP7/WM1buJqxddgHAzkuyoxvztSoMCthWIcmYjdeKNbsgCp8I8eO8cJjUKoUuh70wdJBSmPiDcg=
  file:
    - resources/public/js/asciinema-player.js
    - resources/public/css/asciinema-player.css
  skip_cleanup: true
  on:
    tags: true
    repo: asciinema/asciinema-player
